#ifndef TS_FEATURES_H
#define TS_FEATURES_H

/* Auto-generated by mini-tsc — do not edit. */
/* Only features/methods referenced by the compiled program are enabled. */

#define TS_NEED_MODULE_FS 1
#define TS_NEED_MODULE_HTTP 1
#define TS_NEED_MODULE_PATH 1
#define TS_NEED_MODULE_PROCESS 1

#define TS_NEED_ARRAY 1
#define TS_NEED_BUFFER 1
#define TS_NEED_HASHMAP 1
#define TS_NEED_MATH 1
#define TS_NEED_PROMISE 1
#define TS_NEED_TIMERS 1
#define TS_NEED_URL 1
#define TS_NEED_WEBSOCKET 1

#define TS_NEED_node_fs_readFile 1
#define TS_NEED_node_fs_readFileSync 1
#define TS_NEED_node_http_createServer 1
#define TS_NEED_node_http_server_listen 1
#define TS_NEED_node_path_join 1
#define TS_NEED_node_process_set_argv 1
#define TS_NEED_ts_math_floor 1
#define TS_NEED_ts_math_random 1

#endif /* TS_FEATURES_H */