export interface BuiltinModule {
  name: string;
  headerFile: string;
  cSourceFile: string;
  functions: BuiltinFunction[];
}

export interface BuiltinFunction {
  tsName: string;
  cName: string;
  signature: string;
}

export const BUILTIN_MODULES: Map<string, BuiltinModule> = new Map([
  ["fs", {
    name: "fs",
    headerFile: "node_fs.h",
    cSourceFile: "node_fs.c",
    functions: [
      /* Synchronous functions */
      { tsName: "readFileSync", cName: "node_fs_readFileSync", signature: "Value node_fs_readFileSync(Value path, Value options)" },
      { tsName: "writeFileSync", cName: "node_fs_writeFileSync", signature: "int node_fs_writeFileSync(Value path, Value data, Value options)" },
      { tsName: "existsSync", cName: "node_fs_existsSync", signature: "int node_fs_existsSync(Value path)" },
      { tsName: "mkdirSync", cName: "node_fs_mkdirSync", signature: "int node_fs_mkdirSync(Value path, Value options)" },
      { tsName: "readdirSync", cName: "node_fs_readdirSync", signature: "Value node_fs_readdirSync(Value path)" },
      { tsName: "unlinkSync", cName: "node_fs_unlinkSync", signature: "int node_fs_unlinkSync(Value path)" },
      { tsName: "statSync", cName: "node_fs_statSync", signature: "Value node_fs_statSync(Value path)" },
      { tsName: "rmdirSync", cName: "node_fs_rmdirSync", signature: "int node_fs_rmdirSync(Value path)" },
      { tsName: "renameSync", cName: "node_fs_renameSync", signature: "int node_fs_renameSync(Value oldPath, Value newPath)" },
      { tsName: "readlinkSync", cName: "node_fs_readlinkSync", signature: "Value node_fs_readlinkSync(Value path)" },
      { tsName: "symlinkSync", cName: "node_fs_symlinkSync", signature: "int node_fs_symlinkSync(Value target, Value path)" },
      { tsName: "chmodSync", cName: "node_fs_chmodSync", signature: "int node_fs_chmodSync(Value path, Value mode)" },
      /* Asynchronous functions */
      { tsName: "readFile", cName: "node_fs_readFile", signature: "Value node_fs_readFile(Value path, Value options)" },
      { tsName: "writeFile", cName: "node_fs_writeFile", signature: "Value node_fs_writeFile(Value path, Value data, Value options)" },
      { tsName: "access", cName: "node_fs_access", signature: "Value node_fs_access(Value path, Value mode)" },
      { tsName: "mkdir", cName: "node_fs_mkdir", signature: "Value node_fs_mkdir(Value path, Value options)" },
      { tsName: "readdir", cName: "node_fs_readdir", signature: "Value node_fs_readdir(Value path)" },
      { tsName: "unlink", cName: "node_fs_unlink", signature: "Value node_fs_unlink(Value path)" },
      { tsName: "stat", cName: "node_fs_stat", signature: "Value node_fs_stat(Value path)" },
      { tsName: "rmdir", cName: "node_fs_rmdir", signature: "Value node_fs_rmdir(Value path)" },
      { tsName: "rename", cName: "node_fs_rename", signature: "Value node_fs_rename(Value oldPath, Value newPath)" },
      { tsName: "readlink", cName: "node_fs_readlink", signature: "Value node_fs_readlink(Value path)" },
      { tsName: "symlink", cName: "node_fs_symlink", signature: "Value node_fs_symlink(Value target, Value path)" },
      { tsName: "chmod", cName: "node_fs_chmod", signature: "Value node_fs_chmod(Value path, Value mode)" },
    ],
  }],
  ["path", {
    name: "path",
    headerFile: "node_path.h",
    cSourceFile: "node_path.c",
    functions: [
      { tsName: "join", cName: "node_path_join", signature: "Value node_path_join(Value* args, int argc)" },
      { tsName: "resolve", cName: "node_path_resolve", signature: "Value node_path_resolve(Value* args, int argc)" },
      { tsName: "basename", cName: "node_path_basename", signature: "Value node_path_basename(Value path, Value ext)" },
      { tsName: "dirname", cName: "node_path_dirname", signature: "Value node_path_dirname(Value path)" },
      { tsName: "extname", cName: "node_path_extname", signature: "Value node_path_extname(Value path)" },
      { tsName: "normalize", cName: "node_path_normalize", signature: "Value node_path_normalize(Value path)" },
      { tsName: "parse", cName: "node_path_parse", signature: "Value node_path_parse(Value path)" },
      { tsName: "format", cName: "node_path_format", signature: "Value node_path_format(Value pathObject)" },
      { tsName: "isAbsolute", cName: "node_path_isAbsolute", signature: "Value node_path_isAbsolute(Value path)" },
      { tsName: "relative", cName: "node_path_relative", signature: "Value node_path_relative(Value from, Value to)" },
    ],
  }],
  ["process", {
    name: "process",
    headerFile: "node_process.h",
    cSourceFile: "node_process.c",
    functions: [
      { tsName: "env", cName: "node_process_env", signature: "Value node_process_env(void)" },
      { tsName: "argv", cName: "node_process_argv", signature: "Value node_process_argv(void)" },
      { tsName: "set_argv", cName: "node_process_set_argv", signature: "void node_process_set_argv(int argc, char** argv)" },
      { tsName: "cwd", cName: "node_process_cwd", signature: "Value node_process_cwd(void)" },
      { tsName: "chdir", cName: "node_process_chdir", signature: "int node_process_chdir(Value dir)" },
      { tsName: "exit", cName: "node_process_exit", signature: "void node_process_exit(Value code)" },
      { tsName: "pid", cName: "node_process_pid", signature: "int node_process_pid(void)" },
      { tsName: "stdin", cName: "node_process_stdin", signature: "Value node_process_stdin(void)" },
      { tsName: "stdout", cName: "node_process_stdout", signature: "Value node_process_stdout(void)" },
      { tsName: "stderr", cName: "node_process_stderr", signature: "Value node_process_stderr(void)" },
      { tsName: "stdin_on", cName: "node_process_stdin_on", signature: "Value node_process_stdin_on(Value event, Value callback)" },
      { tsName: "stdout_on", cName: "node_process_stdout_on", signature: "Value node_process_stdout_on(Value event, Value callback)" },
      { tsName: "stderr_on", cName: "node_process_stderr_on", signature: "Value node_process_stderr_on(Value event, Value callback)" },
      { tsName: "stream_toString", cName: "node_process_stream_toString", signature: "Value node_process_stream_toString(Value val)" },
      { tsName: "stdout_write", cName: "node_process_stdout_write", signature: "Value node_process_stdout_write(Value data)" },
      { tsName: "stderr_write", cName: "node_process_stderr_write", signature: "Value node_process_stderr_write(Value data)" },
      { tsName: "stdout_cursorTo", cName: "node_process_stdout_cursorTo", signature: "Value node_process_stdout_cursorTo(Value x, Value y)" },
      { tsName: "stderr_cursorTo", cName: "node_process_stderr_cursorTo", signature: "Value node_process_stderr_cursorTo(Value x, Value y)" },
      { tsName: "stdout_moveCursor", cName: "node_process_stdout_moveCursor", signature: "Value node_process_stdout_moveCursor(Value dx, Value dy)" },
      { tsName: "stderr_moveCursor", cName: "node_process_stderr_moveCursor", signature: "Value node_process_stderr_moveCursor(Value dx, Value dy)" },
      { tsName: "stdout_clearScreenDown", cName: "node_process_stdout_clearScreenDown", signature: "Value node_process_stdout_clearScreenDown(void)" },
      { tsName: "stderr_clearScreenDown", cName: "node_process_stderr_clearScreenDown", signature: "Value node_process_stderr_clearScreenDown(void)" },
      { tsName: "stdout_clearLine", cName: "node_process_stdout_clearLine", signature: "Value node_process_stdout_clearLine(Value dir)" },
      { tsName: "stderr_clearLine", cName: "node_process_stderr_clearLine", signature: "Value node_process_stderr_clearLine(Value dir)" },
    ],
  }],
  ["os", {
    name: "os",
    headerFile: "node_os.h",
    cSourceFile: "node_os.c",
    functions: [
      { tsName: "platform", cName: "node_os_platform", signature: "Value node_os_platform(void)" },
      { tsName: "hostname", cName: "node_os_hostname", signature: "Value node_os_hostname(void)" },
      { tsName: "totalmem", cName: "node_os_totalmem", signature: "double node_os_totalmem(void)" },
      { tsName: "freemem", cName: "node_os_freemem", signature: "double node_os_freemem(void)" },
      { tsName: "arch", cName: "node_os_arch", signature: "Value node_os_arch(void)" },
      { tsName: "cpus", cName: "node_os_cpus", signature: "Value node_os_cpus(void)" },
      { tsName: "userInfo", cName: "node_os_userInfo", signature: "Value node_os_userInfo(void)" },
      { tsName: "type", cName: "node_os_type", signature: "Value node_os_type(void)" },
      { tsName: "release", cName: "node_os_release", signature: "Value node_os_release(void)" },
      { tsName: "uptime", cName: "node_os_uptime", signature: "double node_os_uptime(void)" },
      { tsName: "loadavg", cName: "node_os_loadavg", signature: "Value node_os_loadavg(void)" },
      { tsName: "homedir", cName: "node_os_homedir", signature: "Value node_os_homedir(void)" },
      { tsName: "tmpdir", cName: "node_os_tmpdir", signature: "Value node_os_tmpdir(void)" },
      { tsName: "version", cName: "node_os_version", signature: "Value node_os_version(void)" },
      { tsName: "machine", cName: "node_os_machine", signature: "Value node_os_machine(void)" },
      { tsName: "EOL", cName: "node_os_EOL", signature: "Value node_os_EOL(void)" },
      { tsName: "devNull", cName: "node_os_devNull", signature: "Value node_os_devNull(void)" },
    ],
  }],
  ["http", {
    name: "http",
    headerFile: "node_http.h",
    cSourceFile: "node_http.c",
    functions: [
      { tsName: "createServer", cName: "node_http_createServer", signature: "Value node_http_createServer(Value callback)" },
      { tsName: "server_listen", cName: "node_http_server_listen", signature: "Value node_http_server_listen(Value serverVal, Value portVal, Value callback)" },
      { tsName: "request", cName: "node_http_request", signature: "Value node_http_request(Value options, Value callback)" },
      { tsName: "get", cName: "node_http_get", signature: "Value node_http_get(Value url, Value callback)" },
    ],
  }],
  ["net", {
    name: "net",
    headerFile: "node_net.h",
    cSourceFile: "node_net.c",
    functions: [
      { tsName: "createServer", cName: "node_net_createServer", signature: "Value node_net_createServer(Value callback)" },
      { tsName: "createConnection", cName: "node_net_createConnection", signature: "Value node_net_createConnection(Value options, Value callback)" },
    ],
  }],
  ["child_process", {
    name: "child_process",
    headerFile: "node_child_process.h",
    cSourceFile: "node_child_process.c",
    functions: [
      { tsName: "execSync", cName: "node_child_process_execSync", signature: "Value node_child_process_execSync(Value command, Value options)" },
      { tsName: "spawn", cName: "node_child_process_spawn", signature: "Value node_child_process_spawn(Value command, Value args, Value options)" },
      { tsName: "exec", cName: "node_child_process_exec", signature: "Value node_child_process_exec(Value command, Value options, Value callback)" },
      { tsName: "execFile", cName: "node_child_process_execFile", signature: "Value node_child_process_execFile(Value file, Value args, Value options, Value callback)" },
      { tsName: "fork", cName: "node_child_process_fork", signature: "Value node_child_process_fork(Value modulePath, Value args, Value options)" },
      { tsName: "on", cName: "node_child_process_on", signature: "Value node_child_process_on(Value child, Value event, Value callback)" },
      { tsName: "stream_on", cName: "node_child_process_stream_on", signature: "Value node_child_process_stream_on(Value child, Value streamName, Value event, Value callback)" },
      { tsName: "send", cName: "node_child_process_send", signature: "Value node_child_process_send(Value child, Value message)" },
    ],
  }],
  ["events", {
    name: "events",
    headerFile: "node_events.h",
    cSourceFile: "node_events.c",
    functions: [
      { tsName: "EventEmitter", cName: "node_events_EventEmitter", signature: "Value node_events_EventEmitter(void)" },
      { tsName: "on", cName: "node_events_on", signature: "Value node_events_on(Value ee, Value event, Value listener)" },
      { tsName: "addListener", cName: "node_events_addListener", signature: "Value node_events_addListener(Value ee, Value event, Value listener)" },
      { tsName: "once", cName: "node_events_once", signature: "Value node_events_once(Value ee, Value event, Value listener)" },
      { tsName: "off", cName: "node_events_off", signature: "Value node_events_off(Value ee, Value event, Value listener)" },
      { tsName: "removeListener", cName: "node_events_removeListener", signature: "Value node_events_removeListener(Value ee, Value event, Value listener)" },
      { tsName: "prependListener", cName: "node_events_prependListener", signature: "Value node_events_prependListener(Value ee, Value event, Value listener)" },
      { tsName: "prependOnceListener", cName: "node_events_prependOnceListener", signature: "Value node_events_prependOnceListener(Value ee, Value event, Value listener)" },
      { tsName: "emit", cName: "node_events_emit", signature: "Value node_events_emit(Value ee, Value event, Value* args, int argc)" },
      { tsName: "removeAllListeners", cName: "node_events_removeAllListeners", signature: "Value node_events_removeAllListeners(Value ee, Value event)" },
      { tsName: "listenerCount", cName: "node_events_listenerCount", signature: "Value node_events_listenerCount(Value ee, Value event)" },
      { tsName: "listeners", cName: "node_events_listeners", signature: "Value node_events_listeners(Value ee, Value event)" },
      { tsName: "rawListeners", cName: "node_events_rawListeners", signature: "Value node_events_rawListeners(Value ee, Value event)" },
      { tsName: "eventNames", cName: "node_events_eventNames", signature: "Value node_events_eventNames(Value ee)" },
      { tsName: "setMaxListeners", cName: "node_events_setMaxListeners", signature: "Value node_events_setMaxListeners(Value ee, Value n)" },
      { tsName: "getMaxListeners", cName: "node_events_getMaxListeners", signature: "Value node_events_getMaxListeners(Value ee)" },
      { tsName: "getEventListeners", cName: "node_events_getEventListeners", signature: "Value node_events_getEventListeners(Value ee, Value event)" },
      { tsName: "defaultMaxListeners", cName: "node_events_defaultMaxListeners", signature: "Value node_events_defaultMaxListeners(void)" },
      { tsName: "setDefaultMaxListeners", cName: "node_events_setDefaultMaxListeners", signature: "Value node_events_setDefaultMaxListeners(Value n)" },
    ],
  }],
  ["readline", {
    name: "readline",
    headerFile: "node_readline.h",
    cSourceFile: "node_readline.c",
    functions: [
      { tsName: "createInterface", cName: "node_readline_createInterface", signature: "Value node_readline_createInterface(Value options)" },
      { tsName: "question", cName: "node_readline_question", signature: "Value node_readline_question(Value rl, Value query, Value callback)" },
      { tsName: "close", cName: "node_readline_close", signature: "Value node_readline_close(Value rl)" },
      { tsName: "on", cName: "node_readline_on", signature: "Value node_readline_on(Value rl, Value event, Value callback)" },
      { tsName: "prompt", cName: "node_readline_prompt", signature: "Value node_readline_prompt(Value rl)" },
      { tsName: "setPrompt", cName: "node_readline_setPrompt", signature: "Value node_readline_setPrompt(Value rl, Value prompt)" },
      { tsName: "getPrompt", cName: "node_readline_getPrompt", signature: "Value node_readline_getPrompt(Value rl)" },
      { tsName: "write", cName: "node_readline_write", signature: "Value node_readline_write(Value rl, Value data)" },
      { tsName: "pause", cName: "node_readline_pause", signature: "Value node_readline_pause(Value rl)" },
      { tsName: "resume", cName: "node_readline_resume", signature: "Value node_readline_resume(Value rl)" },
      { tsName: "clearLine", cName: "node_readline_clearLine", signature: "void node_readline_clearLine(Value stream, Value dir)" },
      { tsName: "cursorTo", cName: "node_readline_cursorTo", signature: "void node_readline_cursorTo(Value stream, Value x, Value y)" },
      { tsName: "moveCursor", cName: "node_readline_moveCursor", signature: "void node_readline_moveCursor(Value stream, Value dx, Value dy)" },
    ],
  }],
  ["crypto", {
    name: "crypto",
    headerFile: "node_crypto.h",
    cSourceFile: "node_crypto.c",
    functions: [
      { tsName: "randomBytes", cName: "node_crypto_randomBytes", signature: "Value node_crypto_randomBytes(Value size)" },
      { tsName: "randomUUID", cName: "node_crypto_randomUUID", signature: "Value node_crypto_randomUUID(void)" },
      { tsName: "createHash", cName: "node_crypto_createHash", signature: "Value node_crypto_createHash(Value algorithm)" },
      { tsName: "createHmac", cName: "node_crypto_createHmac", signature: "Value node_crypto_createHmac(Value algorithm, Value key)" },
      { tsName: "pbkdf2Sync", cName: "node_crypto_pbkdf2Sync", signature: "Value node_crypto_pbkdf2Sync(Value password, Value salt, Value iterations, Value keylen, Value digest)" },
      { tsName: "pbkdf2", cName: "node_crypto_pbkdf2", signature: "Value node_crypto_pbkdf2(Value password, Value salt, Value iterations, Value keylen, Value digest, Value callback)" },
      { tsName: "md5", cName: "node_crypto_md5", signature: "Value node_crypto_md5(Value data)" },
      { tsName: "sha1", cName: "node_crypto_sha1", signature: "Value node_crypto_sha1(Value data)" },
      { tsName: "sha256", cName: "node_crypto_sha256", signature: "Value node_crypto_sha256(Value data)" },
      { tsName: "sha512", cName: "node_crypto_sha512", signature: "Value node_crypto_sha512(Value data)" },
      { tsName: "hmac_sha256", cName: "node_crypto_hmac_sha256", signature: "Value node_crypto_hmac_sha256(Value key, Value data)" },
      { tsName: "scryptSync", cName: "node_crypto_scryptSync", signature: "Value node_crypto_scryptSync(Value password, Value salt, Value keylen)" },
      { tsName: "hashUpdate", cName: "node_crypto_hashUpdate", signature: "Value node_crypto_hashUpdate(Value hash, Value data)" },
      { tsName: "hashDigest", cName: "node_crypto_hashDigest", signature: "Value node_crypto_hashDigest(Value hash, Value encoding)" },
    ],
  }],
  ["assert", {
    name: "assert",
    headerFile: "node_assert.h",
    cSourceFile: "node_assert.c",
    functions: [
      { tsName: "ok", cName: "node_assert_ok", signature: "void node_assert_ok(Value value, Value message)" },
      { tsName: "assert", cName: "node_assert_assert", signature: "void node_assert_assert(Value value, Value message)" },
      { tsName: "equal", cName: "node_assert_equal", signature: "void node_assert_equal(Value actual, Value expected, Value message)" },
      { tsName: "notEqual", cName: "node_assert_notEqual", signature: "void node_assert_notEqual(Value actual, Value expected, Value message)" },
      { tsName: "strictEqual", cName: "node_assert_strictEqual", signature: "void node_assert_strictEqual(Value actual, Value expected, Value message)" },
      { tsName: "notStrictEqual", cName: "node_assert_notStrictEqual", signature: "void node_assert_notStrictEqual(Value actual, Value expected, Value message)" },
      { tsName: "deepEqual", cName: "node_assert_deepEqual", signature: "void node_assert_deepEqual(Value actual, Value expected, Value message)" },
      { tsName: "deepStrictEqual", cName: "node_assert_deepStrictEqual", signature: "void node_assert_deepStrictEqual(Value actual, Value expected, Value message)" },
      { tsName: "notDeepEqual", cName: "node_assert_notDeepEqual", signature: "void node_assert_notDeepEqual(Value actual, Value expected, Value message)" },
      { tsName: "notDeepStrictEqual", cName: "node_assert_notDeepStrictEqual", signature: "void node_assert_notDeepStrictEqual(Value actual, Value expected, Value message)" },
      { tsName: "fail", cName: "node_assert_fail", signature: "void node_assert_fail(Value message)" },
      { tsName: "ifError", cName: "node_assert_ifError", signature: "void node_assert_ifError(Value value)" },
      { tsName: "throws", cName: "node_assert_throws", signature: "void node_assert_throws(Value fn, Value errorOrMessage)" },
      { tsName: "doesNotThrow", cName: "node_assert_doesNotThrow", signature: "void node_assert_doesNotThrow(Value fn, Value message)" },
      { tsName: "match", cName: "node_assert_match", signature: "void node_assert_match(Value str, Value regexp, Value message)" },
      { tsName: "doesNotMatch", cName: "node_assert_doesNotMatch", signature: "void node_assert_doesNotMatch(Value str, Value regexp, Value message)" },
    ],
  }],
]);

export function getBuiltinModule(name: string): BuiltinModule | undefined {
  return BUILTIN_MODULES.get(name);
}
