#ifndef TS_FEATURES_H
#define TS_FEATURES_H

/* Auto-generated by mini-tsc — do not edit. */
/* Only features/methods referenced by the compiled program are enabled. */

#define TS_NEED_MODULE_PROCESS 1

#define TS_NEED_ARRAY 1
#define TS_NEED_HASHMAP 1
#define TS_NEED_WEBSOCKET 1

#define TS_NEED_node_process_set_argv 1

#endif /* TS_FEATURES_H */